server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

feign:
  circuitbreaker:
    enabled: true


spring:
  main:
    #允许存在多个Feign调用相同Service的接口
    allow-bean-definition-overriding: true
